apps:
  payment-app:
    name: "payment-app"
    dockerImage: "nginx:latest"
  basket-app:
    name: "basket-app"
    dockerImage: "nginx:latest"
  checkout-app:
    name: "checkout-app"
    dockerImage: "nginx:latest"
  catalog-app:
    name: "catalog-app"
    dockerImage: "nginx:latest"
